"""Minimal TypeScript client codegen from ActionRegistry (optional power)."""

from __future__ import annotations

from typing import Iterable, Optional

from ux_channel.host.registry import ActionRegistry


def generate_ts_client(
    registry: ActionRegistry,
    *,
    module_name: str = "UidActions",
    endpoint: str = "/ux-channel/action",
) -> str:
    """
    Emit a small TS module with typed action name union + run helpers.

    Not full arg typing (needs pydantic models) — stable action names + DX shell.
    """
    names = registry.names()
    union = " | ".join(f'"{n}"' for n in names) if names else "string"
    lines = [
        "/* auto-generated by ux_channel.codegen — do not edit by hand */",
        f"export type UidActionName = {union};",
        "",
        "export interface UidIntent {",
        '  uid: "1";',
        "  action: UidActionName | string;",
        "  args?: Record<string, unknown>;",
        "  cap?: string;",
        "  target?: string;",
        "  request_id?: string;",
        "  idempotency_key?: string;",
        "  accept_stream?: boolean;",
        "}",
        "",
        "export interface UidResult {",
        "  uid: string;",
        "  ok: boolean;",
        "  ops: Array<{ op: string; [k: string]: unknown }>;",
        "  error?: { code: string; message: string };",
        "  meta?: Record<string, unknown>;",
        "}",
        "",
        f'const DEFAULT_ENDPOINT = "{endpoint}";',
        "",
        "export async function runUidAction(",
        "  action: UidActionName | string,",
        "  args: Record<string, unknown> = {},",
        "  opts: { cap?: string; target?: string; endpoint?: string; idempotency_key?: string } = {}",
        "): Promise<UidResult> {",
        "  const endpoint = opts.endpoint || DEFAULT_ENDPOINT;",
        "  const intent: UidIntent = {",
        '    uid: "1",',
        "    action,",
        "    args,",
        "    cap: opts.cap,",
        "    target: opts.target,",
        "    request_id: `req_${Math.random().toString(36).slice(2)}`,",
        "    idempotency_key: opts.idempotency_key,",
        "  };",
        "  const res = await fetch(endpoint, {",
        '    method: "POST",',
        '    headers: { "Content-Type": "application/ux-channel+json", Accept: "application/ux-channel+json", "X-Channel": "1" },',
        "    credentials: \"same-origin\",",
        "    body: JSON.stringify(intent),",
        "  });",
        "  const body = (await res.json()) as UidResult;",
        "  if (typeof window !== 'undefined' && (window as any).uxChannel?.applyResult) {",
        "    await (window as any).uxChannel.applyResult(body);",
        "  }",
        "  return body;",
        "}",
        "",
        f"export const {module_name} = {{",
    ]
    for n in names:
        safe = n.replace(".", "_").replace("-", "_")
        lines.append(
            f'  {safe}: (args: Record<string, unknown> = {{}}, opts: {{ cap?: string; target?: string }} = {{}}) => runUidAction("{n}", args, opts),'
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def write_ts_client(registry: ActionRegistry, path: str, **kwargs) -> str:
    src = generate_ts_client(registry, **kwargs)
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
    return path
