"""Compatibility alias — implementation: ``ux_channel.transport.batch``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.batch`` / ``from ux_channel.batch import ...``
Preferred:     ``from ux_channel.transport.batch import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.transport.batch")
_sys.modules[__name__] = _impl
