"""Compatibility alias — implementation: ``ux_channel.bridge_meta.bridge_protocol``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.bridge_protocol`` / ``from ux_channel.bridge_protocol import ...``
Preferred:     ``from ux_channel.bridge_meta.bridge_protocol import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.bridge_meta.bridge_protocol")
_sys.modules[__name__] = _impl
