"""Compatibility alias — implementation: ``ux_channel.host.catalog``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.catalog`` / ``from ux_channel.catalog import ...``
Preferred:     ``from ux_channel.host.catalog import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.catalog")
_sys.modules[__name__] = _impl
