"""Compatibility alias — implementation: ``ux_channel.ops_dx.codegen``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.codegen`` / ``from ux_channel.codegen import ...``
Preferred:     ``from ux_channel.ops_dx.codegen import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.ops_dx.codegen")
_sys.modules[__name__] = _impl
