"""Compatibility alias — implementation: ``ux_channel.transport.concurrency``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.concurrency`` / ``from ux_channel.concurrency import ...``
Preferred:     ``from ux_channel.transport.concurrency import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.transport.concurrency")
_sys.modules[__name__] = _impl
