"""Compatibility alias — implementation: ``ux_channel.host.day1``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.day1`` / ``from ux_channel.day1 import ...``
Preferred:     ``from ux_channel.host.day1 import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.day1")
_sys.modules[__name__] = _impl
