"""Compatibility alias — implementation: ``ux_channel.protocol.encode``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.encode`` / ``from ux_channel.encode import ...``
Preferred:     ``from ux_channel.protocol.encode import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.protocol.encode")
_sys.modules[__name__] = _impl
