"""Compatibility alias — implementation: ``ux_channel.protocol.error_map``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.error_map`` / ``from ux_channel.error_map import ...``
Preferred:     ``from ux_channel.protocol.error_map import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.protocol.error_map")
_sys.modules[__name__] = _impl
