"""Compatibility alias — implementation: ``ux_channel.host.flow``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.flow`` / ``from ux_channel.flow import ...``
Preferred:     ``from ux_channel.host.flow import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.flow")
_sys.modules[__name__] = _impl
