"""Compatibility alias — implementation: ``ux_channel.bridge_meta.guest_runtime``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.guest_runtime`` / ``from ux_channel.guest_runtime import ...``
Preferred:     ``from ux_channel.bridge_meta.guest_runtime import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.bridge_meta.guest_runtime")
_sys.modules[__name__] = _impl
