"""Compatibility alias — implementation: ``ux_channel.ops_dx.info``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.info`` / ``from ux_channel.info import ...``
Preferred:     ``from ux_channel.ops_dx.info import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.ops_dx.info")
_sys.modules[__name__] = _impl
