"""Compatibility alias — implementation: ``ux_channel.foundations.io_channel``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.io_channel`` / ``from ux_channel.io_channel import ...``
Preferred:     ``from ux_channel.foundations.io_channel import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.foundations.io_channel")
_sys.modules[__name__] = _impl
