"""Compatibility alias — implementation: ``ux_channel.protocol.jsonutil``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.jsonutil`` / ``from ux_channel.jsonutil import ...``
Preferred:     ``from ux_channel.protocol.jsonutil import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.protocol.jsonutil")
_sys.modules[__name__] = _impl
