"""Compatibility alias — implementation: ``ux_channel.realtime.media``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.media`` / ``from ux_channel.media import ...``
Preferred:     ``from ux_channel.realtime.media import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.realtime.media")
_sys.modules[__name__] = _impl
