"""Compatibility alias — implementation: ``ux_channel.transport.middleware``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.middleware`` / ``from ux_channel.middleware import ...``
Preferred:     ``from ux_channel.transport.middleware import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.transport.middleware")
_sys.modules[__name__] = _impl
