"""Compatibility alias — implementation: ``ux_channel.paint.morph_ir``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.morph_ir`` / ``from ux_channel.morph_ir import ...``
Preferred:     ``from ux_channel.paint.morph_ir import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.paint.morph_ir")
_sys.modules[__name__] = _impl
