"""Compatibility alias — implementation: ``ux_channel.host.nonce``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.nonce`` / ``from ux_channel.nonce import ...``
Preferred:     ``from ux_channel.host.nonce import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.nonce")
_sys.modules[__name__] = _impl
