"""Compatibility alias — implementation: ``ux_channel.protocol.ops``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.ops`` / ``from ux_channel.ops import ...``
Preferred:     ``from ux_channel.protocol.ops import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.protocol.ops")
_sys.modules[__name__] = _impl
