"""Compatibility alias — implementation: ``ux_channel.paint.placement``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.placement`` / ``from ux_channel.placement import ...``
Preferred:     ``from ux_channel.paint.placement import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.paint.placement")
_sys.modules[__name__] = _impl
