"""Compatibility alias — implementation: ``ux_channel.bridge_meta.plugins``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.plugins`` / ``from ux_channel.plugins import ...``
Preferred:     ``from ux_channel.bridge_meta.plugins import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.bridge_meta.plugins")
_sys.modules[__name__] = _impl
