"""Compatibility alias — implementation: ``ux_channel.security_plane.policy``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.policy`` / ``from ux_channel.policy import ...``
Preferred:     ``from ux_channel.security_plane.policy import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.security_plane.policy")
_sys.modules[__name__] = _impl
