"""Compatibility alias — implementation: ``ux_channel.paint.projections``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.projections`` / ``from ux_channel.projections import ...``
Preferred:     ``from ux_channel.paint.projections import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.paint.projections")
_sys.modules[__name__] = _impl
