"""Compatibility alias — implementation: ``ux_channel.security_plane.push_security``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.push_security`` / ``from ux_channel.push_security import ...``
Preferred:     ``from ux_channel.security_plane.push_security import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.security_plane.push_security")
_sys.modules[__name__] = _impl
