"""Compatibility alias — implementation: ``ux_channel.transport.push``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.push`` / ``from ux_channel.push import ...``
Preferred:     ``from ux_channel.transport.push import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.transport.push")
_sys.modules[__name__] = _impl
