"""Compatibility alias — implementation: ``ux_channel.foundations.quantity``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.quantity`` / ``from ux_channel.quantity import ...``
Preferred:     ``from ux_channel.foundations.quantity import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.foundations.quantity")
_sys.modules[__name__] = _impl
