"""Compatibility alias — implementation: ``ux_channel.host.recipes``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.recipes`` / ``from ux_channel.recipes import ...``
Preferred:     ``from ux_channel.host.recipes import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.recipes")
_sys.modules[__name__] = _impl
