"""Compatibility alias — implementation: ``ux_channel.host.region_directory``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.region_directory`` / ``from ux_channel.region_directory import ...``
Preferred:     ``from ux_channel.host.region_directory import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.region_directory")
_sys.modules[__name__] = _impl
