"""Compatibility alias — implementation: ``ux_channel.host.region_component``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.region_component`` / ``from ux_channel.region_component import ...``
Preferred:     ``from ux_channel.host.region_component import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.region_component")
_sys.modules[__name__] = _impl
