"""Compatibility alias — implementation: ``ux_channel.paint.render``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.render`` / ``from ux_channel.render import ...``
Preferred:     ``from ux_channel.paint.render import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.paint.render")
_sys.modules[__name__] = _impl
