"""Compatibility alias — implementation: ``ux_channel.realtime.sfu``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.sfu`` / ``from ux_channel.sfu import ...``
Preferred:     ``from ux_channel.realtime.sfu import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.realtime.sfu")
_sys.modules[__name__] = _impl
