"""Compatibility alias — implementation: ``ux_channel.host.ssr_state``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.ssr_state`` / ``from ux_channel.ssr_state import ...``
Preferred:     ``from ux_channel.host.ssr_state import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.ssr_state")
_sys.modules[__name__] = _impl
