"""Compatibility alias — implementation: ``ux_channel.host.state``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.state`` / ``from ux_channel.state import ...``
Preferred:     ``from ux_channel.host.state import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.state")
_sys.modules[__name__] = _impl
