"""Compatibility alias — implementation: ``ux_channel.host.testing``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.testing`` / ``from ux_channel.testing import ...``
Preferred:     ``from ux_channel.host.testing import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.host.testing")
_sys.modules[__name__] = _impl
