"""Compatibility alias — implementation: ``ux_channel.ops_dx.ticket_revoke``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.ticket_revoke`` / ``from ux_channel.ticket_revoke import ...``
Preferred:     ``from ux_channel.ops_dx.ticket_revoke import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.ops_dx.ticket_revoke")
_sys.modules[__name__] = _impl
