"""Compatibility alias — implementation: ``ux_channel.protocol.types``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.types`` / ``from ux_channel.types import ...``
Preferred:     ``from ux_channel.protocol.types import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.protocol.types")
_sys.modules[__name__] = _impl
