"""Compatibility alias — implementation: ``ux_channel.realtime.webrtc_ui``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.webrtc_ui`` / ``from ux_channel.webrtc_ui import ...``
Preferred:     ``from ux_channel.realtime.webrtc_ui import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.realtime.webrtc_ui")
_sys.modules[__name__] = _impl
