"""Compatibility alias — implementation: ``ux_channel.realtime.whip``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.whip`` / ``from ux_channel.whip import ...``
Preferred:     ``from ux_channel.realtime.whip import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("ux_channel.realtime.whip")
_sys.modules[__name__] = _impl
