#!/usr/bin/env python3
"""Repo health — required files, stale paths, broken links, forbidden layout.

Also flags dead session-only recovery paths so GitHub stays the durable source.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED = [
    "README.md",
    "DOCS.md",
    "MENTAL_MODEL.md",
    "LONGEVITY.md",
    "START_HERE.md",
    "TESTING.md",
    "NAMING.md",
    "AUTOMATION.md",
    "ARCHITECTURE.md",
    "STRUCTURE.md",
    "verify.sh",
    "Makefile",
    "python/src/ux_channel/PACKAGE_MAP.json",
    "python/src/ux_channel/api/__init__.py",
    "python/src/ux_channel/host/channel.py",
    "python/src/ux_channel/host/stores.py",
    "python/src/ux_channel/protocol/capability.py",
    "python/src/ux_channel/catalog/catalog.json",
    "python/tests/gate/test_package_layout_contract.py",
    "python/tests/gate/test_api_regions.py",
    "rust/src/lib.rs",
    "conformance/manifest.json",
    "scripts/sync_python_layout.py",
    "scripts/check_longevity.py",
    "scripts/repo_health.py",
    "docs/archive/HARDENING_STATUS.md",
    "RECOVERY.md",
]

STALE = [
    r"ux_channel\.day1\b",
    r"ux_channel\.ops_dx\b",
    r"ux_channel\.bridge_meta\b",
    r"ux_channel\.paint\b",
    r"ux_channel\.host\.dx\b",
    r"host/dx\.py",
    r"python/src/ux_channel/day1/",
    r"python/src/ux_channel/paint/",
    r"python/src/ux_channel/ops_dx/",
    r"python/src/ux_channel/zones/",
]

# Dead agent-session / sandbox paths must not be presented as source of truth
STALE_SOFT: list[tuple[str, str]] = [
    (
        r"/home/workdir/",
        "session-only path — point at GitHub main or patches/ instead",
    ),
    (
        r"/tmp/ux-channel",
        "ephemeral path — not a durable recovery source",
    ),
]

# Files allowed to mention historical / migration names
STALE_EXEMPT_NAMES = {
    "CHANGELOG.md",
    "STABILITY.md",
    "NAMING.md",
    "MENTAL_MODEL.md",
    "LONGEVITY.md",
    "START_HERE.md",
    "TESTING.md",
    "STRUCTURE.md",
    "PUBLIC_API_FREEZE.md",
    "AUTOMATION.md",
    "repo_health.py",
}

# Recovery docs may mention old zip names as historical once, but not /home/workdir
SOFT_EXEMPT_REL = {
    "scripts/repo_health.py",
    "AUTOMATION.md",
}

LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")

SKIP_DIR_PARTS = {
    ".git",
    "__pycache__",
    "target",
    "node_modules",
    ".venv",
    "dist",
    "build",
}


def skip_path(p: Path) -> bool:
    try:
        p.relative_to(ROOT)
    except ValueError:
        return True
    if any(part in SKIP_DIR_PARTS for part in p.parts):
        return True
    return False


def check_forbidden_layout(root: Path) -> list[str]:
    issues: list[str] = []
    pkg = root / "python" / "src" / "ux_channel"
    for name in ("day1", "ops_dx", "bridge_meta", "paint", "zones", "security_plane", "agents"):
        if (pkg / name).exists():
            issues.append(f"FORBIDDEN package dir: ux_channel/{name}")
    if (pkg / "host" / "dx.py").exists():
        issues.append("FORBIDDEN: host/dx.py (use host/channel.py)")
    if (pkg / "host" / "state.py").exists():
        issues.append("FORBIDDEN: host/state.py (use host/stores.py)")
    return issues


def check_catalog_generated_marker() -> list[str]:
    issues: list[str] = []
    cat = ROOT / "python/src/ux_channel/catalog/catalog.json"
    if not cat.exists():
        return ["MISSING catalog/catalog.json"]
    text = cat.read_text(encoding="utf-8", errors="replace")
    if "GENERATED by scripts/sync_python_layout.py" not in text and "this catalog is generated" not in text:
        issues.append("catalog.json missing generated marker — run sync_python_layout.py")
    return issues


def main() -> int:
    issues: list[str] = []
    issues.extend(check_forbidden_layout(ROOT))
    issues.extend(check_catalog_generated_marker())

    for r in REQUIRED:
        if not (ROOT / r).exists():
            issues.append(f"MISSING required file: {r}")

    verify = (ROOT / "verify.sh").read_text(encoding="utf-8", errors="replace")
    if "pytest" not in verify:
        issues.append("verify.sh missing Python pytest")
    if "cargo test" not in verify:
        issues.append("verify.sh missing cargo test")
    if "uxc_check" not in verify:
        issues.append("verify.sh missing uxc_check")
    if "sync_python_layout" not in verify:
        issues.append("verify.sh missing layout sync check")
    ci = (ROOT / ".github/workflows/ci.yml").read_text(encoding="utf-8", errors="replace")
    if "verify.sh" not in ci:
        issues.append("CI workflow does not run verify.sh")
    if "repo_health" not in ci:
        issues.append("CI workflow does not run repo_health")

    makefile = (ROOT / "Makefile").read_text(encoding="utf-8", errors="replace")
    for target in ("regen", "layout", "verify"):
        if target not in makefile:
            issues.append(f"Makefile missing target hint: {target}")

    for p in ROOT.rglob("*"):
        if not p.is_file() or skip_path(p):
            continue
        if p.suffix not in {".md", ".sh", ".py", ".rs", ".toml", ".yml", ".yaml"} and p.name not in {
            "verify.sh",
            "startup-peer.sh",
            "Makefile",
        }:
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        rel = p.relative_to(ROOT).as_posix()

        if p.name not in STALE_EXEMPT_NAMES and rel != "scripts/repo_health.py":
            for pat in STALE:
                if re.search(pat, text):
                    issues.append(f"STALE path {pat!r} in {rel}")

        if rel not in SOFT_EXEMPT_REL:
            for pat, hint in STALE_SOFT:
                if re.search(pat, text):
                    issues.append(f"DEAD path in {rel}: {hint} (matched {pat!r})")

        if p.suffix == ".md":
            if rel.startswith("docs/archive/"):
                continue
            for m in LINK_RE.finditer(text):
                href = m.group(2).strip()
                if href.startswith(("http://", "https://", "mailto:", "#")):
                    continue
                href_path = href.split("#", 1)[0].split("?", 1)[0]
                if not href_path:
                    continue
                target = (p.parent / href_path).resolve()
                try:
                    target.relative_to(ROOT.resolve())
                except ValueError:
                    continue
                if not target.exists():
                    issues.append(f"BROKEN LINK in {rel}: ({href_path})")

    if issues:
        print(f"repo_health: {len(issues)} issue(s)")
        for i in issues:
            print(" -", i)
        return 1
    print("repo_health: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
