#!/usr/bin/env python3
"""Single source of truth for Python host package layout.

Reads:  python/src/ux_channel/PACKAGE_MAP.json
Writes: top-level compatibility aliases, zones catalog, package __init__ stubs

Usage:
  python3 scripts/sync_python_layout.py          # regenerate
  python3 scripts/sync_python_layout.py --check  # CI: fail if drift

Do not hand-edit generated shims. Change PACKAGE_MAP.json (or move a module
into a cohesive package and re-run sync).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "python" / "src" / "ux_channel"
MAP_PATH = PKG / "PACKAGE_MAP.json"

SHIM_TEMPLATE = '''\
"""Compatibility alias — implementation: ``{target}``.

GENERATED by scripts/sync_python_layout.py — do not hand-edit.
Stable import: ``import ux_channel.{stem}`` / ``from ux_channel.{stem} import ...``
Preferred:     ``from {target} import ...``
"""
from __future__ import annotations

from importlib import import_module as _import_module
import sys as _sys

_impl = _import_module("{target}")
_sys.modules[__name__] = _impl
'''

PKG_INIT_TEMPLATE = '''\
"""Cohesive package: **{pkg}**

{doc}

Modules: {modules}

Import: ``from ux_channel.{pkg}.MODULE import Symbol``
Legacy: ``from ux_channel.MODULE import Symbol`` (generated alias).

Source of truth: PACKAGE_MAP.json · sync: scripts/sync_python_layout.py
"""
from __future__ import annotations

MEMBERS = {members!r}
PACKAGE = {pkg!r}
__all__ = ["MEMBERS", "PACKAGE"]
'''



def load_map() -> dict:
    if not MAP_PATH.exists():
        raise SystemExit(f"missing {MAP_PATH}")
    return json.loads(MAP_PATH.read_text(encoding="utf-8"))


def expected_shim(stem: str, pkg: str) -> str:
    target = f"ux_channel.{pkg}.{stem}"
    return SHIM_TEMPLATE.format(stem=stem, target=target)


def regenerate(meta: dict) -> list[str]:
    actions: list[str] = []
    modules: dict[str, str] = meta["modules"]

    # Cohesive package __init__ files
    by_pkg: dict[str, list[str]] = {}
    for stem, pkg in modules.items():
        by_pkg.setdefault(pkg, []).append(stem)
    for pkg, stems in sorted(by_pkg.items()):
        stems = sorted(stems)
        init = PKG / pkg / "__init__.py"
        doc = meta.get("package_docs", {}).get(pkg, "Cohesive implementation package.")
        text = PKG_INIT_TEMPLATE.format(
            pkg=pkg, doc=doc, modules=", ".join(stems), members=stems
        )
        if not init.exists() or init.read_text(encoding="utf-8") != text:
            init.parent.mkdir(parents=True, exist_ok=True)
            init.write_text(text, encoding="utf-8")
            actions.append(f"write {init.relative_to(ROOT)}")

    # Top-level aliases
    for stem, pkg in sorted(modules.items()):
        path = PKG / f"{stem}.py"
        text = expected_shim(stem, pkg)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            actions.append(f"write {path.relative_to(ROOT)}")

    # Remove stale shims (top-level .py that claim to be generated aliases but not in map)
    allowed_top = set(modules) | {"__init__", "__main__", "_version"}
    for path in PKG.glob("*.py"):
        if path.stem in allowed_top:
            continue
        body = path.read_text(encoding="utf-8", errors="replace")
        if "GENERATED by scripts/sync_python_layout" in body or "Compatibility alias" in body or "Compatibility shim" in body:
            path.unlink()
            actions.append(f"remove stale {path.relative_to(ROOT)}")

    # zones/catalog.json — machine catalog
    catalog = {
        pkg: {stem: f"ux_channel.{pkg}.{stem}" for stem in sorted(stems)}
        for pkg, stems in sorted(by_pkg.items())
    }
    catalog["legacy_aliases"] = {
        stem: f"ux_channel.{pkg}.{stem}" for stem, pkg in sorted(modules.items())
    }
    catalog["public_entry"] = meta.get("public_entry", {})
    catalog["rust_parity"] = meta.get("rust_parity", {})
    zones = PKG / "zones"
    zones.mkdir(exist_ok=True)
    cat_path = zones / "catalog.json"
    cat_text = json.dumps(catalog, indent=2) + "\n"
    if not cat_path.exists() or cat_path.read_text(encoding="utf-8") != cat_text:
        cat_path.write_text(cat_text, encoding="utf-8")
        actions.append("write zones/catalog.json")

    # Minimal zones/__init__.py navigator (stable API)
    zinit = zones / "__init__.py"
    ztext = '''\
"""Package map navigator — generated catalog, not an implementation layer.

    from ux_channel.zones import catalog, help_public
    print(help_public())
"""
from __future__ import annotations

import json
from pathlib import Path

_CAT = Path(__file__).resolve().parent / "catalog.json"
catalog: dict = json.loads(_CAT.read_text(encoding="utf-8"))

__all__ = ["catalog", "help_public", "help_package"]


def help_public() -> str:
    pe = catalog.get("public_entry", {})
    rp = catalog.get("rust_parity", {})
    lines = [
        "Public entry: " + str(pe.get("preferred", "ux_channel.day1")),
        "Host: " + ", ".join(pe.get("host_api", [])),
        "Cap (Rust-parity): " + ", ".join(pe.get("cap_api", [])),
        "Rust parity map: " + ", ".join(f"{k}→{v}" for k, v in rp.items()),
    ]
    return "\\n".join(lines) + "\\n"


def help_package(name: str) -> str:
    members = catalog.get(name)
    if not members:
        return f"unknown package: {name}\\n"
    rows = "\\n".join(f"  {k:28} {v}" for k, v in sorted(members.items()))
    return f"package={name}\\n{rows}\\n"
'''
    if not zinit.exists() or zinit.read_text(encoding="utf-8") != ztext:
        zinit.write_text(ztext, encoding="utf-8")
        actions.append("write zones/__init__.py")

    return actions


def check(meta: dict) -> list[str]:
    """Return list of problems (empty = clean)."""
    problems: list[str] = []
    modules: dict[str, str] = meta["modules"]

    for stem, pkg in modules.items():
        impl = PKG / pkg / f"{stem}.py"
        if not impl.exists():
            problems.append(f"missing implementation {pkg}/{stem}.py")
        shim = PKG / f"{stem}.py"
        if not shim.exists():
            problems.append(f"missing alias {stem}.py")
            continue
        want = expected_shim(stem, pkg)
        got = shim.read_text(encoding="utf-8")
        if got != want:
            problems.append(f"drift in alias {stem}.py (run sync_python_layout.py)")

    # No unexpected generated leftovers
    for path in PKG.glob("*.py"):
        if path.stem in modules or path.stem in {"__init__", "__main__", "_version"}:
            continue
        body = path.read_text(encoding="utf-8", errors="replace")
        if "GENERATED by scripts/sync_python_layout" in body:
            problems.append(f"stale generated alias {path.name}")

    # Public import smoke (only when check is run with PYTHONPATH set by caller)
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="CI mode: fail on drift")
    args = ap.parse_args()
    meta = load_map()

    if args.check:
        # ensure regenerated expectation without writing? compare only
        problems = check(meta)
        # also require import
        sys.path.insert(0, str(ROOT / "python" / "src"))
        try:
            from ux_channel import CapService, Channel, Region, RegionBook  # noqa: WPS433
            from ux_channel.day1 import Channel as C2  # noqa: WPS433
            from ux_channel.zones import help_public, catalog  # noqa: WPS433
            assert Channel is C2
            assert hasattr(CapService, "mint") and not hasattr(CapService("dev-secret-key-32chars-minimum!!!!"), "sign")
            assert "host" in catalog or "legacy_aliases" in catalog
            _ = help_public()
            from ux_channel.regions import _id_str  # noqa: F401 — private via alias
        except Exception as exc:
            problems.append(f"import smoke failed: {exc}")
        if problems:
            print("sync_python_layout --check FAILED:", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            return 1
        print(f"sync_python_layout: OK ({len(meta['modules'])} modules, no drift)")
        return 0

    actions = regenerate(meta)
    # post-write check
    problems = check(meta)
    if problems:
        print("regenerate left problems:", problems, file=sys.stderr)
        return 1
    if actions:
        print("sync_python_layout: updated")
        for a in actions[:30]:
            print(" ", a)
        if len(actions) > 30:
            print(f"  … +{len(actions)-30} more")
    else:
        print("sync_python_layout: already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
