#!/usr/bin/env python3
"""Validate package layout and regenerate the navigation catalog.

Source of truth: python/src/ux_channel/PACKAGE_MAP.json (v3+)

  python3 scripts/sync_python_layout.py          # regenerate catalog only
  python3 scripts/sync_python_layout.py --check  # CI validate + identity smoke

Package ``__init__.py`` files are **always hand-maintained**. This script never
overwrites them. There is no magic comment marker and no shell/Python export
named MANUAL_PUBLIC_API (that was an internal layout guard — removed).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "python" / "src" / "ux_channel"
MAP_PATH = PKG / "PACKAGE_MAP.json"

CATALOG_INIT = '''"""Package catalog — navigation helpers (not an implementation plane).

    from ux_channel.catalog import help_public, help_package, catalog
"""
from __future__ import annotations

import json
from pathlib import Path

catalog = json.loads((Path(__file__).parent / "catalog.json").read_text(encoding="utf-8"))
__all__ = ["catalog", "help_public", "help_package"]


def help_public() -> str:
    pe = catalog.get("public_entry", {})
    rp = catalog.get("rust_parity", {})
    pkgs = ", ".join(sorted(catalog.get("packages", {})))
    return (
        f"Public: {pe.get('preferred', 'ux_channel.api')}\\n"
        f"Host API: {', '.join(pe.get('host_api', []))}\\n"
        f"Cap (Rust-parity): {', '.join(pe.get('cap_api', []))}\\n"
        f"Packages: {pkgs}\\n"
        f"Policy: {catalog.get('policy')}\\n"
        f"Rust parity: {rp}\\n"
    )


def help_package(name: str) -> str:
    members = catalog.get("packages", {}).get(name)
    if not members:
        return f"unknown package: {name}\\n"
    rows = "\\n".join(f"  {k:28} {v}" for k, v in sorted(members.items()))
    return f"package={name}\\n{rows}\\n"
'''


def load_map() -> dict:
    return json.loads(MAP_PATH.read_text(encoding="utf-8"))


def packages_from_meta(meta: dict) -> dict[str, list[str]]:
    if isinstance(meta.get("packages"), dict) and meta["packages"]:
        return {k: list(v) for k, v in meta["packages"].items()}
    by_pkg: dict[str, list[str]] = {}
    for key, pkg in meta.get("modules", {}).items():
        stem = key.split(".", 1)[1] if "." in key else key
        by_pkg.setdefault(pkg, []).append(stem)
    return by_pkg


def regenerate(meta: dict) -> list[str]:
    """Regenerate catalog.json (+ catalog package init if missing). Never touch other __init__.py."""
    actions: list[str] = []
    by_pkg = packages_from_meta(meta)

    catalog_data = {
        "policy": "no_shims",
        "map_version": meta.get("version"),
        "note": "Package __init__.py files are hand-maintained; this catalog is generated.",
        "public_entry": meta.get("public_entry", {}),
        "rust_parity": meta.get("rust_parity", {}),
        "packages": {
            pkg: {s: f"ux_channel.{pkg}.{s}" for s in sorted(set(stems))}
            for pkg, stems in sorted(by_pkg.items())
        },
    }
    catalog_dir = PKG / "catalog"
    catalog_dir.mkdir(exist_ok=True)
    cat_path = catalog_dir / "catalog.json"
    cat_text = json.dumps(catalog_data, indent=2) + "\n"
    if not cat_path.exists() or cat_path.read_text(encoding="utf-8") != cat_text:
        cat_path.write_text(cat_text, encoding="utf-8")
        actions.append("write catalog/catalog.json")

    zinit = catalog_dir / "__init__.py"
    # catalog package is the only generated init (navigation helpers)
    if not zinit.exists() or "help_public" not in zinit.read_text(encoding="utf-8"):
        zinit.write_text(CATALOG_INIT, encoding="utf-8")
        actions.append("write catalog/__init__.py")

    # refuse leftover top-level shims
    allowed = {"__init__", "__main__", "_version"}
    for path in PKG.glob("*.py"):
        if path.stem in allowed:
            continue
        body = path.read_text(encoding="utf-8", errors="replace")
        if "Compatibility" in body or "GENERATED by scripts" in body or "_sys.modules[__name__]" in body:
            path.unlink()
            actions.append(f"removed shim {path.name}")
    return actions


def check(meta: dict) -> list[str]:
    problems: list[str] = []
    by_pkg = packages_from_meta(meta)

    for pkg, stems in by_pkg.items():
        for stem in stems:
            if not (PKG / pkg / f"{stem}.py").exists():
                problems.append(f"missing {pkg}/{stem}.py")

    for pkg, stems in by_pkg.items():
        d = PKG / pkg
        if not d.is_dir():
            problems.append(f"missing package dir {pkg}/")
            continue
        on_disk = {p.stem for p in d.glob("*.py") if p.name != "__init__.py"}
        mapped = set(stems)
        for extra in sorted(on_disk - mapped):
            problems.append(f"unmapped module {pkg}/{extra}.py")
        for missing in sorted(mapped - on_disk):
            problems.append(f"mapped but missing {pkg}/{missing}.py")

    allowed = {"__init__", "__main__", "_version"}
    for path in PKG.glob("*.py"):
        if path.stem not in allowed:
            problems.append(f"forbidden top-level module (no shims): {path.name}")

    if not (PKG / "api" / "__init__.py").exists():
        problems.append("missing public package api/")
    if not (PKG / "render" / "__init__.py").exists():
        problems.append("missing package render/")
    for legacy in ("paint", "ops_dx", "bridge_meta", "day1", "zones", "security_plane", "agents"):
        if (PKG / legacy).exists():
            problems.append(f"legacy package {legacy}/ must not exist")

    # magic comment must not reappear
    for p in PKG.rglob("__init__.py"):
        text = p.read_text(encoding="utf-8", errors="replace")
        if "MANUAL_PUBLIC_API" in text:
            problems.append(f"stale layout marker MANUAL_PUBLIC_API in {p.relative_to(PKG)}")

    if int(meta.get("version") or 0) >= 3:
        for key, pkg in meta.get("modules", {}).items():
            if "." not in key:
                problems.append(f"v3 module key must be package.stem, got {key!r}")
            elif not key.startswith(pkg + "."):
                problems.append(f"v3 module key {key!r} does not match package {pkg!r}")

    sys.path.insert(0, str(ROOT / "python" / "src"))
    try:
        from ux_channel import CapService, Channel, Region, RegionBook, agents, state
        from ux_channel.api import CapService as ACS
        from ux_channel.api import Channel as C2
        from ux_channel.api import state as api_state
        from ux_channel.agent_runtime import AgentRunner
        from ux_channel.agent_runtime.policy import AgentPolicy
        from ux_channel.asgi import mount_channel
        from ux_channel.devtools import errors as devtools_errors
        from ux_channel.host.channel import Channel as C3
        from ux_channel.host.regions import RegionBook as RB
        from ux_channel.host.regions import _id_str  # noqa: F401
        from ux_channel.host.state_api import state as state_fn
        from ux_channel.host.stores import MemoryStateStore  # noqa: F401
        from ux_channel.protocol import CapService as PCS
        from ux_channel.protocol import errors as protocol_errors
        from ux_channel.protocol import morph as pmorph
        from ux_channel.protocol.capability import CapService as CS
        from ux_channel.render import morph_ir
        from ux_channel.render.renderers import HtmlRenderer
        from ux_channel.security import policy as security_policy
        from ux_channel.wire import encode, encode_cxb
        from ux_channel import CapService as RCS
        from ux_channel import morph as rmorph
        from ux_channel import state as rstate

        assert Channel is C2 is C3
        assert RegionBook is RB
        assert CapService is CS is ACS is PCS is RCS
        assert hasattr(Channel, "describe") and not hasattr(Channel, "mental_model")
        svc = CapService("dev-secret-key-32chars-minimum!!!!")
        assert hasattr(svc, "mint") and not hasattr(svc, "sign")
        assert callable(state_fn) and api_state is rstate is state_fn
        assert callable(agents)
        assert pmorph is rmorph
        assert encode and encode_cxb and callable(mount_channel)
        assert AgentRunner and AgentPolicy
        assert security_policy is not None
        assert protocol_errors is not None and devtools_errors is not None
        assert protocol_errors is not devtools_errors
        _ = morph_ir, HtmlRenderer
    except Exception as exc:
        problems.append(f"import smoke: {exc}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    meta = load_map()
    if not args.check:
        actions = regenerate(meta)
        print("sync_python_layout:", "updated" if actions else "already up to date")
        for a in actions[:20]:
            print(" ", a)
    problems = check(meta)
    if problems:
        print("FAILED:", file=sys.stderr)
        for p in problems:
            print(" -", p, file=sys.stderr)
        return 1
    n = sum(len(v) for v in packages_from_meta(meta).values())
    print(f"sync_python_layout: OK ({n} modules in {len(packages_from_meta(meta))} packages, no shims)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
