#!/usr/bin/env python3
"""Validate cohesive package layout (no shims / no aliases).

Source of truth: python/src/ux_channel/PACKAGE_MAP.json

  python3 scripts/sync_python_layout.py          # regenerate package __init__ + catalog
  python3 scripts/sync_python_layout.py --check  # CI

Policy: implementations live only under cohesive packages. Public API is
``ux_channel`` root + ``ux_channel.api``. There are no top-level module shims.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "python" / "src" / "ux_channel"
MAP_PATH = PKG / "PACKAGE_MAP.json"

PKG_INIT = '''\
"""Cohesive package: **{pkg}**

{doc}

Modules: {modules}

Import: ``from ux_channel.{pkg}.MODULE import Symbol``
Public apps: ``from ux_channel.api import …`` or ``from ux_channel import …``

Source of truth: PACKAGE_MAP.json
"""
from __future__ import annotations

MEMBERS = {members!r}
PACKAGE = {pkg!r}
__all__ = ["MEMBERS", "PACKAGE"]
'''

CATALOG_INIT = '''\
"""Package catalog — navigation helpers (not an implementation plane).

    from ux_channel.catalog import help_public, help_package, catalog
"""
from __future__ import annotations

import json
from pathlib import Path

catalog = json.loads((Path(__file__).parent / "catalog.json").read_text(encoding="utf-8"))
__all__ = ["catalog", "help_public", "help_package"]


def help_public() -> str:
    pe = catalog.get("public_entry", {})
    rp = catalog.get("rust_parity", {})
    pkgs = ", ".join(sorted(catalog.get("packages", {})))
    return (
        f"Public: {pe.get('preferred', 'ux_channel.api')}\\n"
        f"Host API: {', '.join(pe.get('host_api', []))}\\n"
        f"Cap (Rust-parity): {', '.join(pe.get('cap_api', []))}\\n"
        f"Packages: {pkgs}\\n"
        f"Policy: {catalog.get('policy')}\\n"
        f"Rust parity: {rp}\\n"
    )


def help_package(name: str) -> str:
    members = catalog.get("packages", {}).get(name)
    if not members:
        return f"unknown package: {name}\\n"
    rows = "\\n".join(f"  {k:28} {v}" for k, v in sorted(members.items()))
    return f"package={name}\\n{rows}\\n"
'''


def load_map() -> dict:
    return json.loads(MAP_PATH.read_text(encoding="utf-8"))


def regenerate(meta: dict) -> list[str]:
    actions: list[str] = []
    modules: dict[str, str] = meta["modules"]
    package_docs = meta.get("package_docs", {})
    by_pkg: dict[str, list[str]] = {}
    for stem, pkg in modules.items():
        by_pkg.setdefault(pkg, []).append(stem)

    for pkg, stems in sorted(by_pkg.items()):
        stems = sorted(stems)
        init = PKG / pkg / "__init__.py"
        doc = package_docs.get(pkg, "Cohesive implementation package.")
        text = PKG_INIT.format(pkg=pkg, doc=doc, modules=", ".join(stems), members=stems)
        init.parent.mkdir(parents=True, exist_ok=True)
        if init.exists() and "MANUAL_PUBLIC_API" in init.read_text(encoding="utf-8"):
            continue  # hand-maintained public package API
        if not init.exists() or init.read_text(encoding="utf-8") != text:
            init.write_text(text, encoding="utf-8")
            actions.append(f"write {init.relative_to(ROOT)}")

    # Refuse shims: any top-level .py other than roots is an error source
    allowed = {"__init__", "__main__", "_version"}
    for path in PKG.glob("*.py"):
        if path.stem in allowed:
            continue
        body = path.read_text(encoding="utf-8", errors="replace")
        if "Compatibility" in body or "GENERATED by scripts" in body or "_sys.modules[__name__]" in body:
            path.unlink()
            actions.append(f"removed shim {path.name}")

    # navigation catalog
    catalog_data = {
        "policy": "no_shims",
        "public_entry": meta.get("public_entry", {}),
        "rust_parity": meta.get("rust_parity", {}),
        "packages": {
            pkg: {s: f"ux_channel.{pkg}.{s}" for s in sorted(stems)}
            for pkg, stems in sorted(by_pkg.items())
        },
    }
    catalog_dir = PKG / "catalog"
    catalog_dir.mkdir(exist_ok=True)
    cat_path = catalog_dir / "catalog.json"
    cat_text = json.dumps(catalog_data, indent=2) + "\n"
    if not cat_path.exists() or cat_path.read_text(encoding="utf-8") != cat_text:
        cat_path.write_text(cat_text, encoding="utf-8")
        actions.append("write catalog/catalog.json")

    zinit = catalog_dir / "__init__.py"
    # preserve hand-written catalog init if marked; else write standard
    if zinit.exists() and "MANUAL_PUBLIC_API" in zinit.read_text(encoding="utf-8"):
        pass
    elif not zinit.exists() or zinit.read_text(encoding="utf-8") != CATALOG_INIT:
        zinit.write_text(CATALOG_INIT, encoding="utf-8")
        actions.append("write catalog/__init__.py")
    return actions


def check(meta: dict) -> list[str]:
    problems: list[str] = []
    modules = meta["modules"]
    for stem, pkg in modules.items():
        if not (PKG / pkg / f"{stem}.py").exists():
            problems.append(f"missing {pkg}/{stem}.py")
    allowed = {"__init__", "__main__", "_version"}
    for path in PKG.glob("*.py"):
        if path.stem not in allowed:
            problems.append(f"forbidden top-level module (no shims): {path.name}")
    if not (PKG / "api" / "__init__.py").exists():
        problems.append("missing public package api/")
    if not (PKG / "render" / "__init__.py").exists():
        problems.append("missing package render/")
    for legacy in ("paint", "ops_dx", "bridge_meta", "day1", "zones", "security_plane", "agents"):
        if (PKG / legacy).exists():
            problems.append(f"legacy package {legacy}/ must not exist")
    sys.path.insert(0, str(ROOT / "python" / "src"))
    try:
        from ux_channel import CapService, Channel, Region, RegionBook
        from ux_channel.api import Channel as C2
        from ux_channel.host.channel import Channel as C3
        from ux_channel.host.regions import RegionBook as RB
        from ux_channel.protocol.capability import CapService as CS
        from ux_channel.render import morph_ir
        from ux_channel.render.renderers import HtmlRenderer

        assert Channel is C2 is C3
        assert RegionBook is RB
        assert CapService is CS
        assert hasattr(Channel, "describe") and not hasattr(Channel, "mental_model")
        svc = CapService("dev-secret-key-32chars-minimum!!!!")
        assert hasattr(svc, "mint") and not hasattr(svc, "sign")
        from ux_channel.host.regions import _id_str  # noqa: F401
        from ux_channel.host.stores import MemoryStateStore  # noqa: F401
        from ux_channel.host.state_api import state as state_fn  # noqa: F401
        assert callable(state_fn)
        _ = morph_ir, HtmlRenderer
        # identity matrix
        from ux_channel.api import CapService as ACS, state as api_state
        from ux_channel.protocol import CapService as PCS, morph as pmorph
        from ux_channel import CapService as RCS, morph as rmorph, state as rstate
        assert ACS is PCS is RCS
        assert api_state is rstate is state_fn
        assert pmorph is rmorph
        from ux_channel.wire import encode, encode_cxb
        from ux_channel.asgi import mount_channel
        assert encode and encode_cxb and callable(mount_channel)
    except Exception as exc:
        problems.append(f"import smoke: {exc}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    meta = load_map()
    if not args.check:
        actions = regenerate(meta)
        print("sync_python_layout:", "updated" if actions else "already up to date")
        for a in actions[:20]:
            print(" ", a)
    problems = check(meta)
    if problems:
        print("FAILED:", file=sys.stderr)
        for p in problems:
            print(" -", p, file=sys.stderr)
        return 1
    print(f"sync_python_layout: OK ({len(meta['modules'])} modules, no shims)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
